# Generated by Django 4.2.1 on 2024-06-02 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customuser_date_joined_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="last_name",
        ),
    ]
