# Generated by Django 4.2.1 on 2023-10-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_crypto_usercrypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercrypto',
            old_name='cryptocurrency',
            new_name='crypto',
        ),
    ]
