# Generated by Django 4.2.1 on 2023-10-26 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_cryptocurrency_usercrypto_crypto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercrypto',
            old_name='is_interested',
            new_name='is_favorited',
        ),
    ]
