# Generated by Django 4.2.1 on 2023-10-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_is_interested_usercrypto_is_favorited'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
