# Generated by Django 4.2.1 on 2023-11-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercrypto',
            name='owned_quantity',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=30),
        ),
    ]
