# Generated by Django 4.2.1 on 2023-11-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tradehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradehistory',
            old_name='market',
            new_name='crypto_market',
        ),
    ]
