# Generated by Django 4.2.1 on 2023-11-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_market_tradehistory_crypto_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='trade_price',
            field=models.DecimalField(decimal_places=0, max_digits=30),
        ),
    ]
