# Generated by Django 4.2.1 on 2023-11-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_tradehistory_trade_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='trade_category',
            field=models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], default='BUY', max_length=200),
        ),
    ]
