# Generated by Django 4.2.1 on 2023-11-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tradehistory_trade_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=200),
        ),
    ]
