# Generated by Django 4.2.1 on 2023-11-12 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_tradehistory_is_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradehistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
