version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A crypto_app worker -l info
    env_file:
      - .env
    volumes:
      - ./crypto_django/db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.beat
    command: celery -A crypto_app beat -l info
    env_file:
      - .env
    volumes:
      - ./crypto_django/db.sqlite3:/app/db.sqlite3
    depends_on:
      - redis